# Generated by Django 5.1.3 on 2024-11-27 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0003_pdtester"),
    ]

    operations = [
        migrations.DeleteModel(
            name="umTester",
        ),
    ]
